### ISSUE TITLE
Стиль написания кода.

### ISSUE THREAD

**Issue by VildanovDenis** [lexantus/number-to-words-ru#2]
В общем-то понятно о чем все. 
Как я уже упомянул у меня vs code по непонятным мне причинам на сохранении сам пробелы раскидывает. Мне особо не принципиально, какой стиль будет, главное чтобы было читабельно. 
У себя в репозиториях я просто все через perttier прогонял, особо не заморачиваясь.

**Comment by lexantus** [comment]
Попробуй WebStorm от Jetbrains

**Comment by lexantus** [comment]
Чуть позже настрою eslint и Travis CI
