### ISSUE TITLE
В JS есть +0 и -0. Предусмотреть эти случаи и написать тесты

### ISSUE THREAD

**Issue by lexantus** [lexantus/number-to-words-ru#6]

**Comment by VildanovDenis** [comment]
Есть ли смысл проверять на '-0' и '+0' ? Сейчас закинул такой тест:
`it('-0', () => {assert.equal(convert(0), 'ноль')});`
`it('+0', () => {assert.equal(convert(0), 'ноль')});`

И он успешно завершился, вернув как и ожидалось ноль, сам index.js я не менял.

**Comment by lexantus** [comment]
Почему в assert-ах  одинковые выражения?
Должно видимо быть
`it('-0', () => {assert.equal(convert(`**-**`0), 'ноль')});`
`it('+0', () => {assert.equal(convert(`**+**`0), 'ноль')});`

**Comment by lexantus** [comment]
Тесты надо добавить в любом случае(даже если они сейчас проходят). Потому что код будет со временем меняться и может что-то сломаться(Как раз об этом и расскажут тесты)

**Comment by VildanovDenis** [comment]
А, сглупил посмотрю
